### ISSUE TITLE
PySAM 3.0.0 causing Jupyter Kernel to die

### ISSUE THREAD

**Issue by grgmiller** [NREL/pysam#107]
Hello PySAM team - thanks for the new release of PySAM 3.0.0. However, after updating the package in my local conda environment, I am noticing that it is repeatedly causing my jupyter kernel to die. After this happened, I set up two identical environments: my original one with PySAM 2.2.4 (which is working fine), and one with PySAM updated to 3.0.0 plus upgrades to any dependencies. When updating to 3.0.0, the only other packages that were updated were the following:

```
The following packages will be UPDATED:

  ca-certificates    conda-forge::ca-certificates-2021.5.3~ --> pkgs/main::ca-certificates-2021.10.26-haa95532_2
  certifi            conda-forge::certifi-2021.5.30-py38ha~ --> pkgs/main::certifi-2021.10.8-py38haa95532_0
  nrel-pysam                                   2.2.3-py38_0 --> 3.0.0-py38_0
  nrel-pysam-stubs                             2.2.4-py38_0 --> 3.0.0-py38_0
  openssl            conda-forge::openssl-1.1.1k-h8ffe710_1 --> pkgs/main::openssl-1.1.1l-h2bbff1b_0
```

Both environments are using the following jupyter-related packages:
```
ipykernel                 6.2.0            py38h595d716_0    conda-forge
ipython                   7.26.0           py38h595d716_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jupyter_client            6.1.12             pyhd8ed1ab_0    conda-forge
jupyter_core              4.7.1            py38haa244fe_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
```
In my script, I am downloading and simulating wind generation data for multiple locations and generators. The script successfully completes the loop several times, and then dies after about the same amount of time, but never consistently on the same pysam function - sometimes it dies when running `tools.SRW_to_wind_data(wtk_path_dict[filename])`, sometimes when running `system_model_wind.execute()`, and sometimes when just retrieving the outputs from the model. 

When I first started running this, the jupyter logs were showing an error with the traitlets package and something about using nested quotes, like ' " " '. However, I've been unable to re-create this error message. Currently, my jupyter logs show the following errors:

```
Error 10:42:23: Kernel died [o [Error]: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: (code: 3221226505). ....
	at c:\Users\gmiller\.vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:66:1023351
	at c:\Users\gmiller\.vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:66:695951
	at c:\Users\gmiller\.vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:66:696169
	at Immediate._onImmediate (c:\Users\gmiller\.vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:66:697734)
	at processImmediate (internal/timers.js:461:21)] {
  category: 'kerneldied',
  errorMessage: ' (code: 3221226505). . \n',
  stdErr: '',
  exitCode: 3221226505,
  reason: ''
} 
Error 10:42:23: KernelProcess Exit Exit - 3221226505,  [o [Error]: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: (code: 3221226505). ....
	at c:\Users\gmiller\.vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:66:1023351
	at c:\Users\gmiller\.vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:66:695951
	at c:\Users\gmiller\.vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:66:696169
	at Immediate._onImmediate (c:\Users\gmiller\.vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:66:697734)
	at processImmediate (internal/timers.js:461:21)] {
  category: 'kerneldied',
  errorMessage: ' (code: 3221226505). . \n',
  stdErr: '',
  exitCode: 3221226505,
  reason: ''
}
Error 10:42:23: Disposing session as kernel process died ExitCode: 3221226505, Reason: undefined
Info 10:42:23: Dispose Kernel process
Info 10:42:23: kill daemon
Error 10:42:23: Raw kernel process exited code: 3221226505
Error 10:42:23: Error in waiting for cell to complete [Error: Canceled future for execute_request message before replies were done
	at t.KernelShellFutureHandler.dispose (c:\Users\gmiller\.vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:51:426364)
	at c:\Users\gmiller\.vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:66:328821
	at Map.forEach (<anonymous>)
	at y._clearKernelState (c:\Users\gmiller\.vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:66:328807)
	at y.dispose (c:\Users\gmiller\.vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:66:322239)
	at c:\Users\gmiller\.vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:51:188455
	at t.swallowExceptions (c:\Users\gmiller\.vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:1:139012)
	at dispose (c:\Users\gmiller\.vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:51:188434)
	at t.RawSession.dispose (c:\Users\gmiller\.vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:104:352774)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)]
Info 10:42:23: Cancel all remaining cells due to dead kernel
Info 10:42:23: Cancel pending cells
```

The only explanation that I have is that pysam 3.0.0 or one of its dependencies is causing this issue, but it makes pysam 3.0.0 unuasable with jupyter at this time. Any ideas that you have about how to fix this issue would be appreciated.

**Comment by dguittet** [comment]
Perhaps this is an issue with the upgraded ca-certificates, certifi or openssl packages. NREL-PySAM doesn't specify a required version for these packages so I'm not sure why they are being upgraded. I wonder if you undid those version upgrades below, would it make any difference?

```  
  ca-certificates    conda-forge::ca-certificates-2021.5.3~ --> pkgs/main::ca-certificates-2021.10.26-haa95532_2
  certifi            conda-forge::certifi-2021.5.30-py38ha~ --> pkgs/main::certifi-2021.10.8-py38haa95532_0
  openssl      
```

**Comment by grgmiller** [comment]
I think that I've isolated the issue specifically to nrel-pysam 3.0.0, and no other packages. Still not sure what is causing it though. nrel-pysam-stubs 3.0.0. seems to work fine with nrel-pysam 2.2.4, and it doesn't seem to be an issue with the jupyter version, the python version, or the dependencies.

1. Cloned my original environment with pysam 2.2.4 and only updated nrel-pysam and nrel-pysam-stubs to 3.0.0, without updating any dependencies (ca-certificates, certifi, openssl). This didn't work - the kernel is still dying. (Using Python 3.8)
2. Cloned my original environment, updated psyam and stubs, including dependences. Then I uninstalled all of the ipython and jupyter packages and reinstalled them to the latest version, to see if the issue was with jupyter. This still didn't work - the kernel crashed. (Using Python 3.8)
3. I installed a fresh environment from a yml file, which uses python 3.9.9, to see if it was a python version issue. Didn't work - kernel still died.
4. I installed a fresh environment from a yml file, but pinned nrel-pysam at 2.2.4 (while allowing nrel-pysam-stubs to use 3.0.0). This uses python 3.9.9. This worked - no errors. So the problem doesn't seem to be in nrel-pysam-stubs 3.0.0
5. I installed a fresh environment from a yml file, but pinned nrel-pysam-stubs at 2.2.4 (while allowing nrel-pysam to use 3.0.0). This also caused the kernel to die

**Comment by dguittet** [comment]
Thanks for the update. PySAM 3.0.0 had made some changes to the Resource Fetcher, so could you see if it's possible to isolate the problem by running the notebook with 3 different loops:

1. running only the download from wtk
2. running above + tools.SRW_to_wind_data(wtk_path_dict[filename])
3. running above + system_model_wind.execute()

**Comment by grgmiller** [comment]
So one interesting thing about all of this is that my python loops successfully execute 14 times, then on the 15th loop, it seems to crash when running execute(). However, if I add a conditional statement to not run execute() on the 15th loop, it then crashes on the 14th loop. Likewise, if I stop the code from running execute() on the 14th and 15th loop, it crashes on the 13th loop. I'm not sure what could be causing this.

However, I am now getting slightly more helpful error text in the jupyter log. I'm now getting a FutureWarning for the traitlets package, which in and of itself shouldn't cause the kernel to die, but perhaps you can make better sense of it.

```
Error 14:49:59: Kernel died [o [Error]: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: (code: 3221226505). warn(....
	at c:\Users\gmiller\.vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:66:1023351
	at c:\Users\gmiller\.vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:66:695951
	at c:\Users\gmiller\.vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:66:696169
	at Immediate._onImmediate (c:\Users\gmiller\.vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:66:697734)
	at processImmediate (internal/timers.js:461:21)] {
  category: 'kerneldied',
  errorMessage: ' (code: 3221226505). warn(. \n',
  stdErr: `C:\\Users\\gmiller\\.conda\\envs\\match_model_3\\lib\\site-packages\\traitlets\\traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.\r\n` +
    '  warn(\r\n' +
    `C:\\Users\\gmiller\\.conda\\envs\\match_model_3\\lib\\site-packages\\traitlets\\traitlets.py:2157: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '136bd902-46fb-4f82-a197-0b2417fe6cae' instead of 'b"136bd902-46fb-4f82-a197-0b2417fe6cae"'.\r\n` +
    '  warn(\r\n',
  exitCode: 3221226505,
  reason: `C:\\Users\\gmiller\\.conda\\envs\\match_model_3\\lib\\site-packages\\traitlets\\traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.\r\n` +
    '  warn(\r\n' +
    `C:\\Users\\gmiller\\.conda\\envs\\match_model_3\\lib\\site-packages\\traitlets\\traitlets.py:2157: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '136bd902-46fb-4f82-a197-0b2417fe6cae' instead of 'b"136bd902-46fb-4f82-a197-0b2417fe6cae"'.\r\n` +
    '  warn(\r\n'
} C:\Users\gmiller\.conda\envs\match_model_3\lib\site-packages\traitlets\traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(
C:\Users\gmiller\.conda\envs\match_model_3\lib\site-packages\traitlets\traitlets.py:2157: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '136bd902-46fb-4f82-a197-0b2417fe6cae' instead of 'b"136bd902-46fb-4f82-a197-0b2417fe6cae"'.
  warn(

Error 14:49:59: KernelProcess Exit Exit - 3221226505, C:\Users\gmiller\.conda\envs\match_model_3\lib\site-packages\traitlets\traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(
C:\Users\gmiller\.conda\envs\match_model_3\lib\site-packages\traitlets\traitlets.py:2157: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '136bd902-46fb-4f82-a197-0b2417fe6cae' instead of 'b"136bd902-46fb-4f82-a197-0b2417fe6cae"'.
  warn(
 [o [Error]: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: (code: 3221226505). warn(....
	at c:\Users\gmiller\.vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:66:1023351
	at c:\Users\gmiller\.vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:66:695951
	at c:\Users\gmiller\.vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:66:696169
	at Immediate._onImmediate (c:\Users\gmiller\.vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:66:697734)
	at processImmediate (internal/timers.js:461:21)] {
  category: 'kerneldied',
  errorMessage: ' (code: 3221226505). warn(. \n',
  stdErr: `C:\\Users\\gmiller\\.conda\\envs\\match_model_3\\lib\\site-packages\\traitlets\\traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.\r\n` +
    '  warn(\r\n' +
    `C:\\Users\\gmiller\\.conda\\envs\\match_model_3\\lib\\site-packages\\traitlets\\traitlets.py:2157: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '136bd902-46fb-4f82-a197-0b2417fe6cae' instead of 'b"136bd902-46fb-4f82-a197-0b2417fe6cae"'.\r\n` +
    '  warn(\r\n',
  exitCode: 3221226505,
  reason: `C:\\Users\\gmiller\\.conda\\envs\\match_model_3\\lib\\site-packages\\traitlets\\traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.\r\n` +
    '  warn(\r\n' +
    `C:\\Users\\gmiller\\.conda\\envs\\match_model_3\\lib\\site-packages\\traitlets\\traitlets.py:2157: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '136bd902-46fb-4f82-a197-0b2417fe6cae' instead of 'b"136bd902-46fb-4f82-a197-0b2417fe6cae"'.\r\n` +
    '  warn(\r\n'
}
Error 14:49:59: Disposing session as kernel process died ExitCode: 3221226505, Reason: undefined
Info 14:49:59: Dispose Kernel process
Info 14:49:59: kill daemon
Error 14:49:59: Raw kernel process exited code: 3221226505
Error 14:49:59: Error in waiting for cell to complete [Error: Canceled future for execute_request message before replies were done
	at t.KernelShellFutureHandler.dispose (c:\Users\gmiller\.vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:51:426364)
	at c:\Users\gmiller\.vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:66:328821
	at Map.forEach (<anonymous>)
	at y._clearKernelState (c:\Users\gmiller\.vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:66:328807)
	at y.dispose (c:\Users\gmiller\.vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:66:322239)
	at c:\Users\gmiller\.vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:51:188455
	at t.swallowExceptions (c:\Users\gmiller\.vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:1:139012)
	at dispose (c:\Users\gmiller\.vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:51:188434)
	at t.RawSession.dispose (c:\Users\gmiller\.vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:104:352774)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)]
Info 14:49:59: Cancel all remaining cells due to dead kernel
Info 14:49:59: Cancel pending cells
```

**Comment by dguittet** [comment]
Unfortunately I have no idea what traitlets is. Can you send me a simplified notebook that reproduces your issue? Right now I am understanding that it only fails when `execute` is called within the loop but looping with just the download and the `SRW_to_wind_data` does not fail.

**Comment by grgmiller** [comment]
I created a simplified notebook but have been unable to re-create the issue in the new notebook, which suggests that perhaps some other piece of the larger code is contributing to the issue - still I'm not sure why the issue would occur when the only difference between the two conda environments is the version of nrel-pysam...

**Comment by grgmiller** [comment]
So I've been digging into this a bit further and running the code in debug mode and seem to have isolated the issue to `PySAM.Windpower.default('WindPowerNone').Turbine.calculate_powercurve()`. This function is in my main loop and excecutes successfully twice for two different powercurve input parameters, but then on the third time around, I get the following error `Exception: rated_wind_speed is not assigned`. 

Looking at the docs (https://nrel-pysam.readthedocs.io/en/master/modules/Windpower.html#PySAM.Windpower.Windpower.Turbine.calculate_powercurve), it appears that `rated_wind_speed` is one of the outputs of calculate_powercurve(), but I'm not sure why this error is not happening the first two times around. It also does not appear that `rated_windspeed` is used as an input for anything else, nor does it appear in the Turbine group.

The issue seems to happen only with a specific one of the wind turbines that I am simulating - when I remove this turbine from the inputs, the code seems to run ok. I'm now wondering if it has something to do with the inputs for this one turbine somehow being infeasible or something and the error handling isn't working correctly?

Here are the input parameters for calculate_powercurve() the turbine that seems to cause this error:

turbine_size  3000
rotor_diameter  129
max_cp  0.45
max_tip_speed  80
max_tip_sp_ratio  8
cut_in  3
cut_out  26
drive_train  0

**Comment by grgmiller** [comment]
Hi @dguittet on a hunch I entered these troublesome parameters into the main SAM module, and it appears that the 129m rotor diameter seems to be causing the following error:

```
equation engine: [32]: eval error in statement list\

fail: [wind_turbine_powercurve_windspeeds,wind_turbine_powercurve_powerout,wind_turbine_rated_wind_speed,wind_turbine_powercurve_err_msg,wind_turbine_powercurve_hub_efficiency] = f( wind.turbine.radio_list_or_design,wind_turbine_powercurve_windspeeds_from_lib,wind_turbine_powercurve_powerout_from_lib,wind_turbine_kw_rating_from_lib,wind_turbine_kw_rating_input,wind_turbine_rotor_diameter_input,wind_turbine_hub_ht,wind.turbine.elevation,wind_resource_model_choice,wind_turbine_max_cp,wind.turbine.max_tip_speed,wind.turbine.max_tspeed_ratio,wind_turbine_cutin,wind_turbine_cut_out,wind.turbine.drive_train )
equation engine: [32]: eval error in statement list\

fail: [wind_turbine_powercurve_windspeeds,wind_turbine_powercurve_powerout,wind_turbine_rated_wind_speed,wind_turbine_powercurve_err_msg,wind_turbine_powercurve_hub_efficiency] = f( wind.turbine.radio_list_or_design,wind_turbine_powercurve_windspeeds_from_lib,wind_turbine_powercurve_powerout_from_lib,wind_turbine_kw_rating_from_lib,wind_turbine_kw_rating_input,wind_turbine_rotor_diameter_input,wind_turbine_hub_ht,wind.turbine.elevation,wind_resource_model_choice,wind_turbine_max_cp,wind.turbine.max_tip_speed,wind.turbine.max_tspeed_ratio,wind_turbine_cutin,wind_turbine_cut_out,wind.turbine.drive_train )
no variables calculated in a single iteration, cannot make progress!
eqn not evaluated: [wind_turbine_powercurve_windspeeds,wind_turbine_powercurve_powerout,wind_turbine_rated_wind_speed,wind_turbine_powercurve_err_msg,wind_turbine_powercurve_hub_efficiency] = f( wind.turbine.radio_list_or_design,wind_turbine_powercurve_windspeeds_from_lib,wind_turbine_powercurve_powerout_from_lib,wind_turbine_kw_rating_from_lib,wind_turbine_kw_rating_input,wind_turbine_rotor_diameter_input,wind_turbine_hub_ht,wind.turbine.elevation,wind_resource_model_choice,wind_turbine_max_cp,wind.turbine.max_tip_speed,wind.turbine.max_tspeed_ratio,wind_turbine_cutin,wind_turbine_cut_out,wind.turbine.drive_train)
```

I'm guessing that this error in the SAM engine is likely what is causing PySAM to crash the Jupyter Kernel. Is this something that can be easily patched in PySAM so that PySAM 3 is functional?

For reference, I'm trying to simulate the powercurve for the following turbine: https://www.siemensgamesa.com/en-int/products-and-services/onshore/wind-turbine-sg-2-9-129

**Comment by dguittet** [comment]
This issue will be fixed in the next release that will be done next week or the week after.

I noticed a work-around is to reduce the max_tip_speed (parameter 5) until it solves. For my test parameters, this required reducing the value from 80 to 60. It'll change the powercurve a bit however.

**Comment by grgmiller** [comment]
Thank you, Darice! 

Do you know if this issue is related to the actual physics of a wind turbine (i.e. 80 is too high a tip speed ratio for the diameter of turbine I entered), or just a bug in the code, or both?

**Comment by dguittet** [comment]
I don't know unfortunately as I'm not familiar with the powercurve fit function and I'm not sure if it's from physics or empirical or reduced-order observations. However, in SAM, this issue has always been treated more like a warning rather than an actual error.

**Comment by grgmiller** [comment]
I just wanted to check to see if there is an anticipated timeline for patching this issue. It is unfortunately making v3.0.0 unusable for me, so I'm stuck using v2.2.4 for now. 

I see that the accompanying SAM ssc issue https://github.com/NREL/SAM/issues/877 has been closed and SAM 2021.12.02 Revision 1 with ssc Revision 268 has been released - does this mean that PySAM 3.0.0 should now work, or will a new release of PySAM need to be made?

**Comment by dguittet** [comment]
Just released the new version! Please let me us know if this error persists.
