### ISSUE TITLE
problem to install pysam

### ISSUE THREAD

**Issue by leo-smi** [NREL/pysam#147]
python 3.10.10
pip 23.1.2

error:
```
Collecting PySAM
  Using cached pysam-0.21.0.tar.gz (4.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [34 lines of output]
      # pysam: cython is available - using cythonize if necessary
      # pysam: htslib mode is shared
      # pysam: HTSLIB_CONFIGURE_OPTIONS=None
      '.' nÆo ‚ reconhecido como um comando interno
      ou externo, um programa oper vel ou um arquivo em lotes.
      '.' nÆo ‚ reconhecido como um comando interno
      ou externo, um programa oper vel ou um arquivo em lotes.
      # pysam: htslib configure options: None
      Traceback (most recent call last):
        File "C:\Users\leand\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\leand\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\leand\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\leand\AppData\Local\Temp\pip-build-env-qka085kp\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\leand\AppData\Local\Temp\pip-build-env-qka085kp\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\leand\AppData\Local\Temp\pip-build-env-qka085kp\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super(_BuildMetaLegacyBackend,
        File "C:\Users\leand\AppData\Local\Temp\pip-build-env-qka085kp\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 383, in <module>
        File "<string>", line 79, in run_make_print_config
        File "C:\Users\leand\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 421, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "C:\Users\leand\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 503, in run
          with Popen(*popenargs, **kwargs) as process:
        File "C:\Users\leand\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Users\leand\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1440, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      FileNotFoundError: [WinError 2] O sistema não pode encontrar o arquivo especificado
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by kandersolar** [comment]
Hi @leo-smi, you might be installing the wrong package.  `pip install pysam` will try to install a [genomics package](https://pypi.org/project/pysam/).  This package is listed on PyPI as [NREL-PySAM](https://pypi.org/project/NREL-PySAM/).  See https://nrel-pysam.readthedocs.io/en/main/installation.html

**Comment by leo-smi** [comment]
Sorry for that.
